### ISSUE TITLE
Testing Repair model functionality

### ISSUE THREAD

**Issue by simondilhas** [simondilhas/qto_buccaneer#4]
Check in this example project: 003_example_repair__public different logical filter combinations and overriding differnt types of values (Bool, Label, ...)

```yaml
project_name: "003_example_repair__public"
project_description: "This is a test project to test the workflow"

buildings:
  - name: "repair_change_value"
    repairs:
      - name: "Normalize PredefinedType casing"
        filter: "type=IfcSpace AND LongName=TRH"
        actions:
          - change_value:
              field: LongName
              value: "HHHH"
      - name: "test second rule"
        filter: "type=IfcDoor"
        actions:
          - change_value:
              field: "Name"
              value: "XxxXX"
```
